version: 0.2

phases:
  install:
    commands:
      # install Node 14
      - echo Installing node...
      - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo Installing deps...
      - npm install
  build:
    commands:
      - echo testing...
      - npm run test -- --watchAll=false
      - echo building...
      - npm run build
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
