version: 0.2

phases:
  install:
    commands:
      # install Node 14
      - echo Installing node...
      - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
      - apt install -y nodejs
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt add -
      - echo Installing yarn...
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt update && apt install --no-install-recommends yarn
      # install Yarn
  pre_build:
    commands:
      - echo Installing deps...
      - yarn
  build:
    commands:
      - echo Testing...
      - yarn test
      - echo building...
      - yarn build
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directiry: dist
